spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/